### ISSUE TITLE
Newer SNES Classic Issues loading FEL

### ISSUE THREAD

**Issue by mattr6** [ClusterM/hakchi2#1228]
Brand new SNES Classic purchased March 2018. Windows 10 machine with signature check disabled. I'm using the cable that came with the SNES. I followed the process to initiate FEL mode (plug USB into pc, hold reset, turn on power, wait, release reset) however the LED comes on almost immediately after I turn power on.

The PC does detect the SNES - I see CLV-S-SNSY in device manager, however LED is on SNES so I'm not in FEL mode. If I plug HDMI cable in I can see the SNES is running.

I have tried multiple machines and multiple ports including usb 2.0 and 3.0 ports with the same results. Is it possible they have changed how these machines enter FEL mode?

**Comment by NiicoD** [comment]
I need to stay at least 10 seconds on reset button... try to keeo it hold until the PC makes a sound...

**Comment by NiicoD** [comment]
To be sure that your SNES is in FEL mode, when you clic on reset button and start the mini console, wait for the USB sound (for me for exmaple, it takes about 5 or 6 seconds, sometimes, more...), then you can clic on install driver.

**Comment by mattr6** [comment]
I discovered that the reset button didn't work. I had to take it apart to fix it. The tolerances on mine were very tight.

**Comment by Darkretro** [comment]
Did you get it to work once reset button fix? cause i have same issue with my 2 Snes i brought last week and i took it apart to hold the reset button manuely and still doesn't work,the snes power up soon as i hit the power button

**Comment by mattr6** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Yes once I fixed the button it worked fine.                                                                                                                                                                         Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: February 9, 2019 8:14 PMTo: hakchi2@noreply.github.comReply to: reply@reply.github.comCc: mattr6@gmail.com; author@noreply.github.comSubject: Re: [ClusterM/hakchi2] Newer SNES Classic Issues loading FEL (#1228)  Did you get it to work once reset button fix?

**Comment by Darkretro** [comment]
Um ok,well i took it apart last night and hold the reset button from the board it self and still not working,also i notice that when i plug the usb cable to my pc it doesnt make a sound like when u plug in a usb cable...i had no issue doing the Nes but Snes really dont wanna cooperate.
