### ISSUE TITLE
Unable to build from latest commit

### ISSUE THREAD

**Issue by stayupthetree** [ClusterM/hakchi2#95]
I get the following 4 errors from Visual Studio when trying to build. http://prntscr.com/e9a35n

**Comment by sanjay900** [comment]
I get the same. I have a feeling some files were not pushed.

**Comment by sanjay900** [comment]
Still have the same problem after https://github.com/ClusterM/hakchi2/commit/05c48013ef1dd208eab51d8bb592b7cd22cc1ab3

**Comment by sanjay900** [comment]
Still a problem after https://github.com/ClusterM/hakchi2/commit/a860691692d64302185a03e9b913174a32e16931

**Comment by torange** [comment]
several of the necessary files can be found on madmonkey's hakchi repo in /mod/hakchi, with the exception of rsync

**Comment by sanjay900** [comment]
Could you link me to that repo?

**Comment by sanjay900** [comment]
Yeah, but even then, we need rsync for any of this to work.
also, still broken as of https://github.com/ClusterM/hakchi2/commit/8c4af6676268ffed40b0c46c8985dc9c6b34a5ce

**Comment by sanjay900** [comment]
I think the issue here is that the .gitignore is ignoring all bin folders, which means that all the bin folders that should be being uploaded are being ignored.

**Comment by sanjay900** [comment]
By accident, it looks like @NoCodeLeftBehind added a bin/ to the .gitignore and this is excluding all bin folders which really isnt helpful. this is also why all the bin files are missing from the retroarch mod as well.

**Comment by sanjay900** [comment]
https://github.com/ClusterM/hakchi2/pull/98

**Comment by sanjay900** [comment]
That would explain why the issue never appeared for @ClusterM and why it has not been solved in the last few commits.

**Comment by bobskorn** [comment]
I still can get it to build after patch @sanjay900 still getting missing file errors

**Comment by sanjay900** [comment]
Yeah, this is something @ClusterM needs to push to after using the patch.
Essentially, the patch is stopping him from uploading the required files for us to compile.

**Comment by bobskorn** [comment]
Ah I see.  Thanks for figuring it out!

**Comment by sanjay900** [comment]
I had an issue where something like this happened to me, so i figured id look into it haha

**Comment by sanjay900** [comment]
I just really want this retroarch mod haha

**Comment by bobskorn** [comment]
You and me both my friend.

**Comment by NoCodeLeftBehind** [comment]
The GitHub Desktop app provided a default .gitignore that excludes /bin. Without it, when you use the app to try to sync your fork to the origin, it treats all of the files that end up being generated in /bin/Debug or /bin/Release during compilation as changed files. While the default .gitignore worked to properly exclude those, it sounds like it unfortunately also caught up files in other /bin sub-folders such as the Linux executables that are needed.

**Comment by sanjay900** [comment]
Oh i see, what you want to ignore then is /bin not bin/

**Comment by bobskorn** [comment]
@sanjay900 did you get the new commit to build properly?   I'm still getting errors in Visual Studio

**Comment by sanjay900** [comment]
Yeah, that are now files missing from tar. Thats easy to fix though, im just copying tar from git bash.

**Comment by bobskorn** [comment]
Can you tell me how?

**Comment by sanjay900** [comment]
Assuming you have git bash installed
go into project ->  hakchi_gui properties -> build events
then replace the pre command with 
set PATH="C:\Program Files\Git\usr\bin"
cd $(ProjectDir)user_mods\retroarch.hmod
bash -c "tar -czvf retroarch.hmod *"
mkdir "$(TargetDir)user_mods\"
move /Y "$(ProjectDir)user_mods\retroarch.hmod\retroarch.hmod" "$(TargetDir)user_mods\"

**Comment by bobskorn** [comment]
I didn't but I will in a min thanks

**Comment by stepik** [comment]
Cluster added missed files

**Comment by stayupthetree** [comment]
Still won't build

**Comment by sanjay900** [comment]
Then again, when i use this build, my nes bootloops, so i dont know what to do at this point.

**Comment by stayupthetree** [comment]
I can't even get an executable out of it, so you are at least further than man

**Comment by bobskorn** [comment]
me either

**Comment by sanjay900** [comment]
If you still can't get this to work, the other option is to just delete the build step entirely and just make the tarball yourself and drop it in.

**Comment by ajmi982** [comment]
can you explain that last comment sanjay900? Im about to try your comment from 4 hours ago.

**Comment by ajmi982** [comment]
I have gitbash installed but i cant find "go into project -> hakchi_gui properties -> build events" inside Visual STudio

**Comment by bobskorn** [comment]
@sanjay900 I followed your instructions but just did it  in Visual Studio and it worked like a champ!!! Thanks  bud.

**Comment by ClusterM** [comment]
Fixed. Sorry :(
