### ISSUE TITLE
Some games not saving? (N64)

### ISSUE THREAD

**Issue by OrisX** [ClusterM/hakchi2#984]
I've been testing some N64 games mainly and I'm noticing that the saves aren't sticking. Banjo-Kazooie, Zelda: OoT and Pokemon Stadium all have had their saves deleted, or maybe they never existed to begin with? I haven't tested it with other N64 games because the ones I have seem to not work (like they go back to the game select screen, but that's an issue for another post). I have tested saves for other games like GB/C/A titles and Genesis titles, and those work fine. Seems to be just N64 saves that don't want to work right.

**Comment by krofinzki** [comment]
This seems to be related to this retroarch issue: https://github.com/ClusterM/retroarch-clover/pull/121

**Comment by Frank-5** [comment]
I also can't save in any of the N64 games I have on my SNES mini.   I tried save state in RetroArch and load state after exiting and running again. Doesn't save.  Nothing to reload is saved.  Also the cool saves into the 4 slots in the SNES screen don't work either.  I've tested SM 64, Mario Kart 64, Asteroids Hyper 64, and a few others.   Games run ok. Just can't save.   2.21c w/ RetroArch 1.0

**Comment by Frank-5** [comment]
All the other GBA, GB, GBC, NES, etc save just fine.

**Comment by Drakonas** [comment]
This is a known issue posted publicly. We are already aware.

**Comment by Frank-5** [comment]
Yes I know.  That was the point I was trying to make.  I failed to mention explicitly that this was already a known (and posted) issue.

**Comment by KMFDManic** [comment]
Since enough people asked, I am gonna fix this issue in my Repo today and update the Core Set, accordingly.  I have been using a workaround to save, up til this point.  But, a more user-friendly install will suffice in this case.  Note: This mainly affects larger games.

**Comment by KMFDManic** [comment]
Fixed in my latest Core Update

https://github.com/KMFDManic/NESC-SNESC-Modifications/releases/

**Comment by OrisX** [comment]
I just downloaded this and tried it. I don't think I installed it incorrectly, but saves for Pokemon Stadium and Ocarina of Time still don't stick for me. Does it matter which module I use to run N64 games, or is it just an issue based on the game's size? Because Banjo-Kazooie's save is working now, which is an improvement from before.

**Comment by KMFDManic** [comment]
@orisX, do one test for me, if you do not mind.  Run Pokemon Stadium and Ocarina of Time in uncompressed format and let me know if the saves work for you.  May need to do a minor adjustment to adapt to them.  Thanks!

**Comment by KMFDManic** [comment]
@OrisX I modified the fix to also apply to 50+ Mb Games for n64.  I can confirm Legend of Zelda - Ocarina of Time now works:)

https://github.com/KMFDManic/NESC-SNESC-Modifications/releases/

**Comment by nekonall** [comment]
can not compressing kirby dreamland 3 get it to save .. i still cant get it to save with out making a suspend point and loading it

**Comment by KMFDManic** [comment]
@nekonall, you using which date RetroArch?  As stated in my latest Update, I will try to make adjustments to compensate for any other games found to have save issues.  Let me know what the date is on the RetroArch you are using. I will look into this game in the morning, otherwise.  In the case of you being able to manually save, but not internally save, this may potentially be related to an sram conflict.  Let me know,and will check things out:)

**Comment by OrisX** [comment]
@KMFDManic Sorry I took so long. I kept the games decompressed and that made them more cooperative as far as loading them, but didn't fix my saves for games like OoT and Pokemon Stadium. I did test the update you put out 11-1, and that got the saves for OoT and Stadium working, but not Stadium 2. I tested the update you came out with today and it still didn't let Stadium 2 keep its saves for me. Everything else I've tested works now, though.

**Comment by KMFDManic** [comment]
@OrisX, I will do another adjustment and ensure Pokemon Stadium 2 works:)  Thanks for the feedback! I will update the Core Set today to take this into account.

**Comment by KMFDManic** [comment]
@nekonall Which Kirby Game are you talking about exactly?  Kirby Dreamland 3 is on SNES.  Just want to make sure I am looking into the correct game.

**Comment by nekonall** [comment]
yeah on snes

**Comment by KMFDManic** [comment]
@nekonall This is a different issue than the GBA/N64 Save Issue.  What are you running it with, Canoe or RetroArch?  I will see what I can do to help:)

**Comment by nekonall** [comment]
canoe retro arch cause slow downs

**Comment by KMFDManic** [comment]
@nekonall You can try the game with 4 different versions of SNES9X (2002, 2005, 2010, 9X).  Sram Saves work fine on 9X.  Canoe is still a WIP, as far as complete game support.  If you want to stick to Canoe, then the Manual Saves, Upon Exiting should work fine for you:)  This has absolutely nothing to do with the GBA/N64 Save issue, however.  This is related to Canoe running a game, versus SNES9X running a game.  2005 tends to run games faster, due to it being less accurate.  But, try the 4 different SNES9X Cores in my set, and see  how things play out, if you want to try them out.

https://github.com/KMFDManic/NESC-SNESC-Modifications

**Comment by Drakonas** [comment]
@nekonall please take this elsewhere and do not hijack someone else's issue for yours. This is a bug tracker not a personal help line. The OP was talking about N64 games, not SNES games. Continue this on Reddit or Discord please.
